name : Deploy
on: [push,workflow_dispatch]
  
jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v6
      - name: Install Node
        uses: action/setup-node@v4
        with:
           node-version: '22'
      - name: print node version
        run: node -v
        
   
   
   
