name : Deploy
on: workflow_dispatch
  
jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        uses: actions/checkout@v6
      - name: Install Node
        uses: cybergavin/setup-nodejs-project@v1
        with:
           node-version: '22'
           lock-file: package-lock.json
      - name: print node version
        run: node -v
        
   
   
   
