name : Deploy
on: [push,workflow_dispatch]
  
jobs:
   test:
    runs-on: ubuntu-latest
    steps:
      - name: get-code
        run: |
            echo "cloningRepo"
            git clone  https://github.com/${{github.repository}}.git 
      